parameters:
    stadline_sugar_crm.client.class: Stadline\SugarCRMBundle\Service\Client
    stadline_sugar_crm.form_type.account.class: Stadline\SugarCRMBundle\Form\Type\AccountType

services:
    stadline_sugar_crm_client:
        class: %stadline_sugar_crm.client.class%
        arguments:
            - %stadline_sugar_crm.config.base_url%
            - %stadline_sugar_crm.config.username%
            - %stadline_sugar_crm.config.password%

    stadline_sugar_crm_form_type.tag:
        class: %stadline_sugar_crm.form_type.account.class%
        tags:
            - { name: form.type, alias: sugar_account }